FROM node:18

RUN apt-get update

RUN mkdir -p /usr/src/app

ARG NEXT_PUBLIC_APP_ENV
ARG NEXT_PUBLIC_BASE_LOCAL
ARG NEXT_PUBLIC_BASE_STAGING
ARG NEXT_PUBLIC_PUBLIC_KEY
ARG NEXT_PUBLIC_PRIVATE_KEY
ARG OKTA_CLIENTID
ARG OKTA_CLIENTSECRET
ARG OKTA_DOMAIN
ARG NEXTAUTH_URL
ARG NEXT_PUBLIC_REDIRECT

ENV PORT 3000
ENV NEXT_PUBLIC_APP_ENV=$NEXT_PUBLIC_APP_ENV
ENV NEXT_PUBLIC_BASE_LOCAL=$NEXT_PUBLIC_BASE_LOCAL
ENV NEXT_PUBLIC_BASE_STAGING=$NEXT_PUBLIC_BASE_STAGING
ENV NEXT_PUBLIC_PUBLIC_KEY=$NEXT_PUBLIC_PUBLIC_KEY
ENV NEXT_PUBLIC_PRIVATE_KEY=$NEXT_PUBLIC_PRIVATE_KEY
ENV OKTA_CLIENTID=$OKTA_CLIENTID
ENV OKTA_CLIENTSECRET=$OKTA_CLIENTSECRET
ENV OKTA_DOMAIN=$OKTA_DOMAIN
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXT_PUBLIC_REDIRECT=$NEXT_PUBLIC_REDIRECT

RUN env

WORKDIR /usr/src/app

COPY package.json /usr/src/app

RUN yarn install 

COPY . /usr/src/app

RUN yarn build

EXPOSE 3000

CMD [ "yarn","start" ]